insert into products (sku, brand, description, unit_price, qty_in_stock) values (50000, 'Twilight', 'sour cream - 250g', 8.76, 17);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50017, 'Phoenix', 'canned chickpeas - 450g', 7.69, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50034, 'Frostbite', 'bell pepper - 130g', 8.36, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50051, 'Zephyr', 'milk - 1L', 5.98, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50068, 'Blizzard', 'cream cheese - 225g', 4.89, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50085, 'Wildfire', 'cola - 330ml', 5.19, 39);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50102, 'Evergreen', 'salmon fillet - 250g', 3.16, 35);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50119, 'Ripple', 'mackerel - 250g', 9.63, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50136, 'Starlight', 'pear - 170g', 9.36, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50153, 'Terra', 'sirloin steak - 350g', 3.32, 27);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50170, 'Phoenix', 'pretzels - 200g', 8.73, 23);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50187, 'Twilight', 'sparkling water - 330ml', 9.35, 15);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50204, 'Terra', 'canned mushrooms - 400g', 8.7, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50221, 'Twilight', 'pretzels - 200g', 9.04, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50238, 'Luminous', 'ground beef - 500g', 9.92, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50255, 'Pulse', 'garlic - 50g', 2.11, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50272, 'Inferno', 'pork belly - 300g', 3.26, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50289, 'Inferno', 'eggplant - 250g', 8.86, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50306, 'Nova', 'potato - 180g', 9.18, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50323, 'Thunderbolt', 'sour cream - 250g', 6.67, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50340, 'Pulse', 'crab - 1kg', 8.62, 16);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50357, 'Wildfire', 'canned chickpeas - 450g', 5.99, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50374, 'Frostbite', 'canned tuna - 170g', 2.71, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50391, 'Galaxy', 'parmesan - 150g', 4.42, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50408, 'Blizzard', 'apple - 180g', 4.26, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50425, 'Twilight', 'pork chop - 250g', 1.29, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50442, 'Twilight', 'trail mix - 150g', 9.55, 35);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50459, 'Radiant', 'mozzarella - 300g', 2.72, 22);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50476, 'Solaris', 'milk - 1L', 6.55, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50493, 'Evergreen', 'cauliflower - 500g', 5.65, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50510, 'Inferno', 'carrot - 100g', 8.41, 17);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50527, 'Silverstone', 'lettuce - 350g', 9.37, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50544, 'Evergreen', 'yogurt - 200g', 6.27, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50561, 'Starlight', 'eggplant - 250g', 9.95, 22);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50578, 'Wildfire', 'garlic - 50g', 6.13, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50595, 'Zephyr', 'mozzarella - 300g', 4.95, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50612, 'Galaxy', 'lemon - 90g', 1.86, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50629, 'Moonbeam', 'mango - 200g', 9.59, 17);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50646, 'Galaxy', 'tuna steak - 200g', 9.09, 49);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50663, 'Whirlwind', 'grapes - 500g', 6.01, 16);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50680, 'Frostbite', 'orange - 160g', 6.03, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50697, 'Phoenix', 'blueberries - 150g', 4.37, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50714, 'Horizon', 'pineapple - 2kg', 2.63, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50731, 'Phoenix', 'canned beans - 440g', 3.41, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50748, 'Radiant', 'chicken thigh - 250g', 2.58, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50765, 'Whirlwind', 'granola bar - 40g', 2.38, 27);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50782, 'Ripple', 'canned corn - 425g', 6.55, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50799, 'Silverstone', 'crackers - 250g', 5.3, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50816, 'Avalanche', 'ham slices - 200g', 4.52, 35);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50833, 'Blizzard', 'avocado - 200g', 2.68, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50850, 'Thunderbolt', 'potato chips - 150g', 3.42, 41);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50867, 'Vortex', 'corn chips - 140g', 3.38, 49);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50884, 'Silverstone', 'deli pork loin - 200g', 4.35, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50901, 'Acme', 'turkey slices - 180g', 2.53, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50918, 'Inferno', 'pork belly - 300g', 2.67, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50935, 'Blizzard', 'milk - 1L', 2.78, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50952, 'Mystique', 'trail mix - 150g', 7.63, 23);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50969, 'Starlight', 'pepperoni - 150g', 4.62, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (50986, 'Horizon', 'celery - 400g', 1.1, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51003, 'Twilight', 'canned mushrooms - 400g', 8.99, 23);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51020, 'Inferno', 'cauliflower - 500g', 8.32, 41);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51037, 'Frostbite', 'canned sardines - 155g', 3.68, 23);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51054, 'Phoenix', 'avocado - 200g', 2.45, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51071, 'Twilight', 'papaya - 1kg', 9.78, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51088, 'Sunrise', 'pastrami - 200g', 7.25, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51105, 'Acme', 'pastrami - 200g', 5.27, 23);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51122, 'Acme', 'zucchini - 200g', 5.83, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51139, 'Vortex', 'bottled water - 500ml', 4.86, 15);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51156, 'Frostbite', 'apple - 180g', 6.9, 42);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51173, 'Thunderbolt', 'cream cheese - 225g', 8.04, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51190, 'Luminous', 'bangus fillet - 300g', 1.34, 18);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51207, 'Horizon', 'trail mix - 150g', 4.0, 30);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51224, 'Frostbite', 'ham slices - 200g', 9.97, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51241, 'Acme', 'cookies - 200g', 6.87, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51258, 'Mystique', 'potato chips - 150g', 8.38, 35);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51275, 'Inferno', 'kiwi - 80g', 4.77, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51292, 'Solaris', 'yogurt - 200g', 7.97, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51309, 'Twilight', 'canned sardines - 155g', 9.32, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51326, 'Starlight', 'sports drink - 600ml', 1.97, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51343, 'Starlight', 'deli pork loin - 200g', 4.91, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51360, 'Inferno', 'orange - 160g', 3.66, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51377, 'Sunrise', 'plum - 75g', 9.4, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51394, 'Cascade', 'canned chickpeas - 450g', 4.74, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51411, 'Starlight', 'garlic - 50g', 9.49, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51428, 'Horizon', 'butter - 200g', 2.45, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51445, 'Nova', 'apple - 180g', 4.24, 18);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51462, 'Silverstone', 'canned pineapple - 560g', 1.2, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51479, 'Zephyr', 'lettuce - 350g', 1.38, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51496, 'Wildfire', 'cherries - 200g', 5.87, 29);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51513, 'Cascade', 'orange juice - 1L', 3.26, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51530, 'Whirlwind', 'shrimp - 300g', 5.02, 38);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51547, 'Solaris', 'cauliflower - 500g', 6.84, 48);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51564, 'Ripple', 'canned tuna - 170g', 8.31, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51581, 'Starlight', 'canned beans - 440g', 6.84, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51598, 'Sapphire', 'lemonade - 1L', 1.45, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51615, 'Blizzard', 'pomegranate - 300g', 8.15, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51632, 'Galaxy', 'ham slices - 200g', 7.44, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51649, 'Whirlwind', 'papaya - 1kg', 9.7, 23);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51666, 'Solaris', 'ground beef - 500g', 2.9, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51683, 'Wildfire', 'rice cakes - 100g', 3.95, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51700, 'Luminous', 'canned corn - 425g', 3.55, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51717, 'Acme', 'cookies - 200g', 3.12, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51734, 'Avalanche', 'ginger - 100g', 4.64, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51751, 'Horizon', 'canned sardines - 155g', 3.57, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51768, 'Luminous', 'popcorn - 100g', 3.77, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51785, 'Avalanche', 'sweet potato - 220g', 2.55, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51802, 'Zephyr', 'orange juice - 1L', 4.47, 26);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51819, 'Sapphire', 'ground beef - 500g', 2.06, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51836, 'Horizon', 'broccoli - 400g', 9.02, 27);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51853, 'Avalanche', 'sparkling water - 330ml', 4.86, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51870, 'Pulse', 'shrimp - 300g', 7.89, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51887, 'Silverstone', 'sparkling water - 330ml', 7.75, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51904, 'Radiant', 'plum - 75g', 2.99, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51921, 'Frostbite', 'blueberries - 150g', 9.02, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51938, 'Twilight', 'lettuce - 350g', 5.46, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51955, 'Solaris', 'blueberries - 150g', 2.81, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51972, 'Eclipse', 'orange - 160g', 8.6, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (51989, 'Eclipse', 'ginger - 100g', 3.92, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52006, 'Inferno', 'mackerel - 250g', 8.33, 18);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52023, 'Solaris', 'mackerel - 250g', 3.0, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52040, 'Acme', 'mushrooms - 200g', 7.84, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52057, 'Inferno', 'canned corn - 425g', 2.63, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52074, 'Silverstone', 'blueberries - 150g', 7.99, 23);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52091, 'Frostbite', 'bell pepper - 130g', 8.68, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52108, 'Sunrise', 'canned corn - 425g', 6.58, 42);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52125, 'Pulse', 'bacon - 250g', 4.06, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52142, 'Luminous', 'watermelon - 3kg', 1.05, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52159, 'Moonbeam', 'watermelon - 3kg', 8.71, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52176, 'Silverstone', 'canned tuna - 170g', 4.16, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52193, 'Avalanche', 'grapes - 500g', 7.39, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52210, 'Mystique', 'sparkling water - 330ml', 3.82, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52227, 'Moonbeam', 'onion - 150g', 8.7, 17);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52244, 'Evergreen', 'butter - 200g', 1.31, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52261, 'Cascade', 'avocado - 200g', 4.39, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52278, 'Silverstone', 'cola - 330ml', 5.49, 30);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52295, 'Silverstone', 'deli pork loin - 200g', 5.38, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52312, 'Frostbite', 'trail mix - 150g', 2.74, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52329, 'Starlight', 'lemon - 90g', 6.56, 48);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52346, 'Nova', 'ham slices - 200g', 7.5, 26);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52363, 'Pulse', 'onion - 150g', 7.37, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52380, 'Phoenix', 'canned tomatoes - 450g', 5.59, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52397, 'Blizzard', 'potato chips - 150g', 9.88, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52414, 'Moonbeam', 'ground beef - 500g', 6.84, 19);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52431, 'Zephyr', 'milk - 1L', 5.24, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52448, 'Whirlwind', 'green beans - 250g', 9.33, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52465, 'Zephyr', 'pepperoni - 150g', 4.45, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52482, 'Frostbite', 'roast beef slices - 150g', 9.9, 38);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52499, 'Sunrise', 'cantaloupe - 1.2kg', 2.76, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52516, 'Sapphire', 'canned soup - 420g', 4.7, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52533, 'Twilight', 'kiwi - 80g', 7.78, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52550, 'Horizon', 'sparkling water - 330ml', 4.36, 39);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52567, 'Avalanche', 'canned tomatoes - 450g', 4.09, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52584, 'Avalanche', 'lemonade - 1L', 4.99, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52601, 'Acme', 'canned corn - 425g', 5.42, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52618, 'Evergreen', 'papaya - 1kg', 1.3, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52635, 'Starlight', 'turkey slices - 180g', 3.96, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52652, 'Inferno', 'cream cheese - 225g', 9.14, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52669, 'Moonbeam', 'corn chips - 140g', 1.76, 41);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52686, 'Ripple', 'mackerel - 250g', 2.03, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52703, 'Wildfire', 'broccoli - 400g', 2.34, 19);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52720, 'Galaxy', 'orange juice - 1L', 6.9, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52737, 'Cascade', 'cottage cheese - 250g', 2.31, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52754, 'Ripple', 'papaya - 1kg', 8.19, 49);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52771, 'Silverstone', 'onion - 150g', 2.1, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52788, 'Vortex', 'crab - 1kg', 6.35, 17);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52805, 'Horizon', 'cantaloupe - 1.2kg', 1.85, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52822, 'Sunrise', 'chicken breast - 300g', 4.89, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52839, 'Evergreen', 'milk tea - 500ml', 3.02, 16);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52856, 'Sunrise', 'cola - 330ml', 3.93, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52873, 'Solaris', 'pastrami - 200g', 1.82, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52890, 'Sapphire', 'deli chicken - 200g', 3.72, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52907, 'Zephyr', 'sweet potato - 220g', 8.67, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52924, 'Sapphire', 'lemonade - 1L', 2.78, 49);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52941, 'Wildfire', 'shrimp - 300g', 7.1, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52958, 'Inferno', 'cookies - 200g', 3.14, 41);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52975, 'Blizzard', 'shrimp - 300g', 8.96, 38);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (52992, 'Evergreen', 'potato - 180g', 6.12, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53009, 'Cascade', 'tomato - 120g', 1.49, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53026, 'Starlight', 'banana - 120g', 4.17, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53043, 'Solaris', 'broccoli - 400g', 2.8, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53060, 'Nova', 'whole chicken - 2kg', 4.21, 17);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53077, 'Mystique', 'kiwi - 80g', 5.17, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53094, 'Pulse', 'pomegranate - 300g', 7.58, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53111, 'Sapphire', 'mango - 200g', 2.42, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53128, 'Sapphire', 'canned tuna - 170g', 5.22, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53145, 'Blizzard', 'pretzels - 200g', 2.09, 39);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53162, 'Horizon', 'spinach - 200g', 4.23, 17);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53179, 'Pulse', 'crab - 1kg', 8.94, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53196, 'Horizon', 'carrot - 100g', 9.96, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53213, 'Wildfire', 'cabbage - 1kg', 5.73, 29);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53230, 'Terra', 'bottled water - 500ml', 4.5, 15);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53247, 'Radiant', 'cauliflower - 500g', 1.23, 29);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53264, 'Zephyr', 'tilapia fillet - 220g', 2.25, 18);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53281, 'Cascade', 'spinach - 200g', 5.54, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53298, 'Luminous', 'canned peas - 400g', 6.56, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53315, 'Inferno', 'pomegranate - 300g', 9.48, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53332, 'Cascade', 'pineapple - 2kg', 9.21, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53349, 'Wildfire', 'pineapple - 2kg', 3.87, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53366, 'Avalanche', 'canned tomatoes - 450g', 2.73, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53383, 'Nova', 'orange - 160g', 1.4, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53400, 'Vortex', 'roast beef slices - 150g', 8.9, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53417, 'Evergreen', 'cauliflower - 500g', 9.32, 15);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53434, 'Terra', 'tomato - 120g', 4.4, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53451, 'Pulse', 'cottage cheese - 250g', 6.35, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53468, 'Luminous', 'tilapia fillet - 220g', 9.33, 48);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53485, 'Terra', 'rice cakes - 100g', 3.19, 16);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53502, 'Acme', 'sparkling water - 330ml', 7.74, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53519, 'Cascade', 'cherries - 200g', 8.12, 27);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53536, 'Acme', 'plum - 75g', 5.28, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53553, 'Twilight', 'mixed nuts - 150g', 6.35, 41);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53570, 'Nova', 'ham slices - 200g', 5.2, 39);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53587, 'Evergreen', 'chicken thigh - 250g', 5.8, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53604, 'Inferno', 'orange - 160g', 6.86, 48);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53621, 'Luminous', 'cantaloupe - 1.2kg', 9.78, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53638, 'Vortex', 'zucchini - 200g', 4.64, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53655, 'Eclipse', 'deli pork loin - 200g', 4.33, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53672, 'Sapphire', 'eggplant - 250g', 3.48, 15);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53689, 'Sunrise', 'deli pork loin - 200g', 1.23, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53706, 'Solaris', 'green beans - 250g', 6.63, 26);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53723, 'Cascade', 'bacon - 250g', 7.34, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53740, 'Twilight', 'deli pork loin - 200g', 1.6, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53757, 'Pulse', 'pork belly - 300g', 5.2, 27);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53774, 'Cascade', 'salami - 200g', 1.72, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53791, 'Starlight', 'cod fillet - 200g', 6.86, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53808, 'Starlight', 'apple - 180g', 2.16, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53825, 'Sapphire', 'energy drink - 350ml', 2.4, 26);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53842, 'Phoenix', 'mango - 200g', 4.92, 47);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53859, 'Silverstone', 'parmesan - 150g', 4.37, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53876, 'Luminous', 'lime - 70g', 3.47, 42);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53893, 'Evergreen', 'ground beef - 500g', 8.27, 27);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53910, 'Wildfire', 'canned peas - 400g', 4.33, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53927, 'Blizzard', 'canned tuna - 170g', 5.71, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53944, 'Blizzard', 'whipping cream - 250ml', 7.55, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53961, 'Horizon', 'canned corn - 425g', 6.74, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53978, 'Acme', 'lime - 70g', 3.41, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (53995, 'Galaxy', 'cucumber - 300g', 5.27, 30);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54012, 'Eclipse', 'crackers - 250g', 3.18, 12);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54029, 'Moonbeam', 'cheese block - 250g', 9.84, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54046, 'Luminous', 'carrot - 100g', 8.05, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54063, 'Eclipse', 'popcorn - 100g', 6.82, 29);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54080, 'Acme', 'orange - 160g', 1.38, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54097, 'Silverstone', 'cod fillet - 200g', 8.82, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54114, 'Blizzard', 'roast beef slices - 150g', 8.29, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54131, 'Acme', 'mixed nuts - 150g', 9.13, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54148, 'Pulse', 'pepperoni - 150g', 7.29, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54165, 'Cascade', 'sparkling water - 330ml', 8.49, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54182, 'Eclipse', 'canned chickpeas - 450g', 2.39, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54199, 'Pulse', 'canned pineapple - 560g', 3.61, 12);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54216, 'Vortex', 'deli corned beef - 180g', 4.04, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54233, 'Ripple', 'tilapia fillet - 220g', 2.84, 37);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54250, 'Frostbite', 'sardines (fresh) - 150g', 4.18, 35);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54267, 'Terra', 'pork chop - 250g', 5.21, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54284, 'Thunderbolt', 'pepperoni - 150g', 9.75, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54301, 'Terra', 'blueberries - 150g', 6.98, 32);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54318, 'Whirlwind', 'blueberries - 150g', 2.62, 25);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54335, 'Vortex', 'pork chop - 250g', 1.95, 27);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54352, 'Horizon', 'shrimp - 300g', 6.72, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54369, 'Acme', 'bell pepper - 130g', 4.36, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54386, 'Luminous', 'deli chicken - 200g', 2.47, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54403, 'Solaris', 'pork belly - 300g', 1.2, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54420, 'Evergreen', 'canned sardines - 155g', 9.46, 22);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54437, 'Nova', 'sour cream - 250g', 5.65, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54454, 'Frostbite', 'pomegranate - 300g', 9.81, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54471, 'Blizzard', 'lettuce - 350g', 9.42, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54488, 'Mystique', 'chicken breast - 300g', 4.45, 40);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54505, 'Whirlwind', 'blueberries - 150g', 1.86, 22);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54522, 'Blizzard', 'cottage cheese - 250g', 4.25, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54539, 'Evergreen', 'cheese block - 250g', 1.98, 31);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54556, 'Avalanche', 'mushrooms - 200g', 4.85, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54573, 'Terra', 'potato chips - 150g', 9.91, 12);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54590, 'Silverstone', 'watermelon - 3kg', 2.05, 49);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54607, 'Solaris', 'cucumber - 300g', 5.02, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54624, 'Inferno', 'sirloin steak - 350g', 9.38, 50);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54641, 'Cascade', 'ground beef - 500g', 1.21, 28);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54658, 'Wildfire', 'whole chicken - 2kg', 1.04, 16);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54675, 'Silverstone', 'canned beans - 440g', 9.04, 41);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54692, 'Blizzard', 'orange - 160g', 3.83, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54709, 'Ripple', 'rice cakes - 100g', 3.9, 36);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54726, 'Mystique', 'papaya - 1kg', 8.56, 44);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54743, 'Acme', 'canned peas - 400g', 8.0, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54760, 'Luminous', 'strawberries - 250g', 7.26, 48);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54777, 'Whirlwind', 'potato chips - 150g', 6.98, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54794, 'Acme', 'pork chop - 250g', 7.77, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54811, 'Frostbite', 'salami - 200g', 6.47, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54828, 'Moonbeam', 'mushrooms - 200g', 1.54, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54845, 'Whirlwind', 'sweet potato - 220g', 3.54, 19);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54862, 'Sunrise', 'trail mix - 150g', 5.2, 20);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54879, 'Terra', 'bangus fillet - 300g', 3.36, 49);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54896, 'Sunrise', 'turkey slices - 180g', 7.08, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54913, 'Pulse', 'canned chickpeas - 450g', 8.47, 13);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54930, 'Pulse', 'pork belly - 300g', 1.26, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54947, 'Solaris', 'cookies - 200g', 1.32, 15);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54964, 'Acme', 'pear - 170g', 1.11, 21);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54981, 'Avalanche', 'zucchini - 200g', 5.53, 41);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (54998, 'Thunderbolt', 'cantaloupe - 1.2kg', 6.21, 43);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55015, 'Frostbite', 'canned beans - 440g', 7.75, 19);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55032, 'Radiant', 'orange - 160g', 3.87, 22);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55049, 'Avalanche', 'mackerel - 250g', 7.85, 12);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55066, 'Cascade', 'cauliflower - 500g', 4.23, 24);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55083, 'Ripple', 'turkey slices - 180g', 7.01, 10);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55100, 'Galaxy', 'mango - 200g', 8.97, 26);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55117, 'Sunrise', 'cucumber - 300g', 1.07, 19);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55134, 'Cascade', 'pork belly - 300g', 6.19, 42);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55151, 'Moonbeam', 'pork chop - 250g', 8.63, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55168, 'Galaxy', 'pear - 170g', 2.63, 14);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55185, 'Cascade', 'canned mushrooms - 400g', 8.03, 33);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55202, 'Twilight', 'plum - 75g', 6.92, 11);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55219, 'Terra', 'green beans - 250g', 1.7, 22);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55236, 'Terra', 'tomato - 120g', 1.98, 45);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55253, 'Mystique', 'spinach - 200g', 5.53, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55270, 'Cascade', 'cherries - 200g', 4.37, 46);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55287, 'Whirlwind', 'potato chips - 150g', 9.05, 34);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55304, 'Luminous', 'pretzels - 200g', 5.94, 48);
insert into products (sku, brand, description, unit_price, qty_in_stock) values (55321, 'Cascade', 'turkey slices - 180g', 4.89, 22);
