"""This module contains the application constants."""

PARSER_LLM_MODEL = "gpt-4o-mini"
RECOMMENDER_LLM_MODEL = "gpt-4o-mini"

PARSER_PROMPT_FILE = "assets/parser_prompt.txt"
PARSER_DUMMY_RESPONSES = "assets/responses/parser"
RECOMMENDER_PROMPT_FILE = "assets/recommender_prompt.txt"
RECOMMENDER_DUMMY_RESPONSES = "assets/responses/recommender"

GROCERY_API_SERVER_BASE_URL = "http://localhost:8000"
GROCERY_API_SERVER_GET_LISTING = "/api/v1/products/"
GROCERY_API_SERVER_GET_PRODUCT = "/api/v1/products/{}"
GROCERY_API_SERVER_HEALTH_CHECK = "/health"

GROCERY_API_SERVER_RETRIES = 3
GROCERY_API_SERVER_BACKOFF_EXPONENTIAL_FACTOR = 1
GROCERY_API_SERVER_BACKOFF_MINIMUM = 2
GROCERY_API_SERVER_BACKOFF_MAXIMUM = 10

OPENAI_PLATFORM_RETRIES = 3
OPENAI_PLATFORM_BACKOFF_EXPONENTIAL_FACTOR = 1
OPENAI_PLATFORM_BACKOFF_MINIMUM = 2
OPENAI_PLATFORM_BACKOFF_MAXIMUM = 10

EMPTY_PRODUCT_DETAILS = {"data": {"sku": -1, "qty_in_stock": -1, "unit_price": -1}}
FUZZY_FILTER_TOP_N = 10
FUZZY_FILTER_MIN_SCORE = 50
